### ISSUE TITLE
Consider making event content types public

### ISSUE THREAD

**Issue by Cnly** [matrix-org/gomatrixserverlib#135]
Currently [Dendrite](https://github.com/matrix-org/dendrite/blob/master/common/eventcontent.go) and [gomatrixserverlib](https://github.com/matrix-org/gomatrixserverlib/blob/master/eventcontent.go) have a number of duplicate event content types (`CreateContent`, `PowerLevelContent`, etc.). We should consider replacing the Dendrite versions with the gomatrixserverlib versions. This will reduce redundant code and also allow Dendrite to easily do power level checks, etc..

Note that we'll probably want to add JSON keys to gomatrixserverlib's event content types first.

**Comment by Cnly** [comment]
cc @anoadragon453

**Comment by anoadragon453** [comment]
Sounds fine to me. Looks like things are missing from both implementations at the moment.

**Comment by babolivier** [comment]
I'd argue that these would better live in gomatrix (with maybe alias types in gomatrixserverlib) so that client apps can benefit from them.

**Comment by Cnly** [comment]
I looked into gomatrix and found that it seems to have its own ways to keep track of events of some types for now, e.g. [`GetMembershipState`](https://github.com/matrix-org/gomatrix/blob/7df988a63f26116f8c9b9c4f2c00b483941b3ba1/room.go#L28). But generally it looks like gomatrix is lacking maintenance... So perhaps we'll still keep these types here, making them public, and consider replacing the stuff in gomatrix later?

**Comment by babolivier** [comment]
Right, makes sense.
