### ISSUE TITLE
Homeserver well known lookup occasionally fails

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/gomatrixserverlib#160]
For example in scalar we are seeing:
```
scalar-live.log-20200326-06:Mar 25 19:44:57 corus docker-scalar-live[690]: time="2020-03-25T19:44:57Z" level=info msg="Failed to LookupUserInfo" error="Get matrix://softzone.ca/_matrix/federation/v1/openid/userinfo?access_token=: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" server_name=softzone.ca
scalar-live.log-20200326-06:Mar 25 19:46:30 corus docker-scalar-live[690]: time="2020-03-25T19:46:30Z" level=info msg="Outgoing request" out.req.ID=4pStqjqRu3DJ out.req.method=GET out.req.uri="matrix://softzone.ca/_matrix/federation/v1/openid/userinfo?access_token=" req.id=m4CfY42GWiYw req.method=POST req.path=/register
scalar-live.log-20200326-06:Mar 25 19:47:00 corus docker-scalar-live[690]: time="2020-03-25T19:47:00Z" level=warning msg="Error sending request to https://softzone.ca:8448/_matrix/federation/v1/openid/userinfo?access_token=: net/http: request canceled while waiting for connection" out.req.ID=4pStqjqRu3DJ out.req.method=GET out.req.uri="matrix://softzone.ca/_matrix/federation/v1/openid/userinfo?access_token=" req.id=m4CfY42GWiYw req.method=POST req.path=/register
```

The well known information is correct http://softzone.ca/.well-known/matrix/server, so unsure why this is failing.

**Comment by Kegsay** [comment]
Because `Client.Timeout exceeded while awaiting headers`. The remote server is taking too long to send back response headers.

**Comment by Half-Shot** [comment]
I don't think so. Gomatrixserverlib is hitting the wrong hostname entirely. It should be hitting `https://softzone.modular.im:443`.

**Comment by Half-Shot** [comment]
Yeah, looking at it:

https://softzone.ca:8448/_matrix/federation/v1/openid/ is timing out, which is probably the cause of `Client.Timeout exceeded while awaiting headers`. The well known endpoint is responding fine, and the json looks well formed. I think this is a bug in the libraries servername resolution code.

**Comment by neilalexander** [comment]
So it looks like the problem is that [this call to `client.LookupUserInfo`](https://github.com/matrix-org/scalar/blob/9d202f1bcd114baf090423bee776541d25fa89e0/accounts/registration.go#L34) passes through `softzone.ca` instead of `softzone.modular.im`. 

To get around that you can do something like this:
```
res, err := gomatrixserverlib.ResolveServer(register.MatrixServerName)
if err != nil {
  // handle error
}

userinfo, err := client.LookupUserInfo(
  req.Context(), res.ServerName, ...
```

**Comment by Half-Shot** [comment]
Ah cool. Yeah we can do that for now. 

I presume the bug is because of the context reusage, as most servers seem to be looked up with success.

**Comment by neilalexander** [comment]
Right - if the request to `https://softzone.ca:8448/_matrix/federation/v1/openid/` takes a long time to time out then it is possible that the original context that is passed into gomatrixserverlib will hit the cancellation first, causing the error you are seeing.

**Comment by Half-Shot** [comment]
```
{
  "WellKnownResult": {
    "m.server": "",
    "result": "Get https://softzone.ca/.well-known/matrix/server: x509: certificate signed by unknown authority"
  },
  "DNSResult": {
    "SRVCName": "",
    "SRVRecords": null,
    "SRVError": {
      "Message": "lookup _matrix._tcp.softzone.ca on 8.8.8.8:53: no such host"
    },
    "Hosts": {
      "softzone.ca": {
        "CName": "softzone.ca.",
        "Addrs": [
          "206.223.191.24"
        ],
        "Error": null
      }
    },
    "Addrs": [
      "206.223.191.24:8448"
    ]
  },
  "ConnectionReports": {},
  "ConnectionErrors": {
    "206.223.191.24:8448": {
      "Message": "Get https://206.223.191.24:8448/_matrix/key/v2/server: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
    }
  },
  "Version": {
    "error": "Get matrix://softzone.ca/_matrix/federation/v1/version: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
  },
  "FederationOK": false
}
```

is what the federation tester says, so I think this is likely it.

**Comment by Half-Shot** [comment]
Certificate is signed by `Go Daddy Secure Certificate Authority - G2`, which presumably isn't recognised by the box we are hosting this on.

**Comment by Half-Shot** [comment]
The owner of the HS has since fixed their certs and it works again. Closing.
