### ISSUE TITLE
Sigining.go

### ISSUE THREAD

**Issue by madguy02** [matrix-org/gomatrixserverlib#47]
I wanted to know how "var object map[string]*json.RawMessage" is behaving,and also the nature of the Rawmessage?

I am actually trying to convert this behavior into JS.So,a little explanation of "func SignJson" is much appreciated

**Comment by NegativeMjark** [comment]
Hi @madguy02.

The behaviour of SignJSON is part of the matrix specification and is documented at https://matrix.org/docs/spec/server_server/unstable.html#signing-json

json.RawMessage is part of the go standard library and is documented at https://golang.org/pkg/encoding/json/#RawMessage

The matrix-js-sdk already has a partial implementation of JSON signing https://github.com/matrix-org/matrix-js-sdk/blob/0f30d21fa270f582d0023214ccca8259d2c6e733/src/crypto/index.js#L1115-L1126

I've added a few comments to the go version to help explain it in #48.

If it helps there is a python implementation at https://github.com/matrix-org/python-signedjson/blob/master/signedjson/sign.py#L26-L53

**Comment by madguy02** [comment]
hii @NegativeMjark thanks for your response
