### ISSUE TITLE
Vanity Go import URLs

### ISSUE THREAD

**Issue by jcgruenhage** [matrix-org/gomatrixserverlib#86]
It might be a good idea to move all the matrix.org go projects to vanity URLs for imports. Not only would this mean a little less code (`import "matrix.org/something"` instead of `import "github.com/matrix-org/something"`), it also means that actually moving the code doesn't break the imports of everyone relying on them. 

Having vanity URLs means that matrix.org would need to serve some html on the import paths, containing a meta tag that instructs go where to find the code. More details on that [here](https://golang.org/cmd/go/#hdr-Remote_import_paths).

**Comment by Kegsay** [comment]
I like this, but it isn't relevant to this project in particular. I'll be bringing this up in discussions in the future though.

**Comment by jcgruenhage** [comment]
I agree that it isn't relevant to the project in particular. If I recall correctly, there was no "right place" for this and I was told to open the issue here.

**Comment by Kegsay** [comment]
That's reasonable, but it's likely to get lost either way. There's other generic Go stuff that we need to be consistent on (e.g using Go modules and not dep/gb/etc, what linting we use, etc) so it's part of a wider group of questions I'll be addressing with the team next week.
