### ISSUE TITLE
Correctly calculating inbound event depth

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/gomatrixserverlib#88]
~~Depth should be ``max(previous_events.depth) + 1``, otherwise we could suffer from the same attacks that Synapse received recently where the depth was escalated to the maximum supported by postgres.~~

Rather than trusting federated depth as Synapse currently does, the current proposal is to make a best guess estimate of what the depth should be on arrival which is tracked in the proposal document linked: 

https://docs.google.com/document/d/16ofbjluy8ZKYL6nt7WLHG4GqSodJUWLUxHhI6xPEjr4

**Comment by Kegsay** [comment]
Is this still relevant? What is the actionable item here?

**Comment by Kegsay** [comment]
Superceded by https://github.com/matrix-org/gomatrixserverlib/issues/187
