### ISSUE TITLE
[discussion] Consider making the const public

### ISSUE THREAD

**Issue by APwhitehat** [matrix-org/gomatrixserverlib#97]
https://github.com/matrix-org/gomatrixserverlib/blob/9f1b58cf2241f98cbd9597ec5c4376356a12656b/eventauth.go#L29-L33

Since go encourages us not to repeat constant string literals, we should make these public and reference them wherever needed.

**Comment by anoadragon453** [comment]
So just `gomatrixserverlib.Join`? That's seems fine.
